---

- block:
  - name: "read linux-headers version"
    shell: "uname -r"
    register: r_uname

  - name: "install basic tools"
    apt:
      name: "{{ item }}"
      state: "present"
    become: true
    with_items:
    - "{{ base_packages }}"
    - "{{ base_packages_additional }}"
