---

- block:
  - name: "Ensure that config directory exists"
    file:
      path: "{{ item }}"
      state: "directory"
    with_items:
    - "/etc/lightdm/lightdm.conf.d"
    - "/etc/X11/xorg.conf.d/"

  - name: "Copy configs"
    copy:
      src: "{{ item }}"
      dest: "/{{ item }}"
    with_items:
    - "etc/lightdm/lightdm.conf.d/10-autologin.conf"
    - "etc/X11/xorg.conf.d/10-keyboard-layout.conf"

- block:
  - name: "Check that user exists"
    shell: "getent passwd {{ user_name }}"
    register: "r_user_exist"
    failed_when: "false"

  #   - name: "Create user"
  #     user:
  #       name: "{{ user_name }}"
  #       password: "{{ password }}"
  #       groups: "sudo"
  #       shell: "/bin/bash"
  #       state: "present"

  - name: "Setup user dot files"
    copy:
      src: "home/user/{{ item }}"
      dest: "/home/{{ user_name }}/.{{ item }}"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
    with_items:
    - "bash_aliases"
    - "bash_profile"
    - "bashrc"
    - "inputrc"
    - "xinitrc"
    - "Xmodmap"

  - name: "Create bin directory"
    file:
      path: "/home/{{ user_name }}/bin"
      state: "directory"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: "Setup user bin files"
    copy:
      src: "home/user/{{ item }}"
      dest: "/home/{{ user_name }}/{{ item }}"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
    with_items:
    - "bin/linkify"

  - name: "Copy XFCE4 config"
    copy:
      src: "home/user/config/xfce4"
      dest: "/home/{{ user_name }}/.config"

  tags:
  - config
