---

- name: "check if user exists"
  shell: "getent passwd {{ os_user_uname.uname }}"
  ignore_errors: true
  register: r_getent_uname

- block:

    # TODO: this sets the same password for all users
    - name: "mkpasswd"
      shell: "mkpasswd -m sha-512 {{ os_user_pword }}"
      register: r_hashed_passwd

    - name: "create os user"
      user:
        name: "{{ os_user_uname  }}"
        password: "{{ r_hashed_passwd.stdout }}"
        groups: "sudo"
        shell: "/bin/bash"
        state: "present"
      become: true

    - name: "setup user dot files"
      copy:
        src: "./home/user/{{ item[1] }}"
        dest: "/home/{{ os_user_uname }}/.{{ item[1] }}"
        owner: "{{ os_user_uname }}"
        group: "{{ os_user_uname }}"
      become: true
      become_user: "{{ os_user_uname }}"
      with_items:
      - ["bash_aliases", "bash_profile", "bashrc", "inputrc", "xinitrc", "Xmodmap"]

    - name: "create bin directory"
      file:
        path: "/home/{{ os_user_uname }}/bin"
        state: "directory"
        owner: "{{ os_user_uname }}"
        group: "{{ os_user_uname }}"
      become: true
      become_user: "{{ os_user_uname }}"

  when: r_getent_uname.rc != 0
