---

- block:
  - name: "create os users"
    user:
      name: "{{ item.uname  }}"
      password: "{{ item.pword }}"
      groups: "sudo"
      shell: "/bin/bash"
      state: "present"
    become: true
    with_items:
    - "{{ os_users }}"

  - name: "setup user dot files"
    copy:
      src: "./home/user/{{ item[1] }}"
      dest: "/home/{{ item[0].uname }}/.{{ item[1] }}"
      owner: "{{ item[0].uname }}"
      group: "{{ item[0].uname }}"
    become: true
    become_user: "{{ item[0].uname }}"
    with_nested:
    - "{{ os_users }}"
    - ["bash_aliases", "bash_profile", "bashrc", "inputrc", "xinitrc", "Xmodmap"]

  - name: "create bin directory"
    file:
      path: "/home/{{ item.uname }}/bin"
      state: "directory"
      owner: "{{ item.uname }}"
      group: "{{ item.uname }}"
    become: true
    become_user: "{{ item.uname }}"
    with_items:
    - "{{ os_users }}"
