---

- block:
  - name: "set apt list"
    copy:
      src: "{{ item }}"
      dest: "/{{ item }}"
    become: true
    with_items:
    - "etc/apt/sources.list.d/java8-debian.list"

  - name: "set key file"
    apt_key:
      keyserver: "keyserver.ubuntu.com"
      state: "present"
      id: "EEA14886"
    become: true

  - name: "install"
    apt:
      name: "{{ item }}"
    become: true
    with_items:
      - "oracle-java8-installer"
      - "oracle-java8-set-default"

  tags:
  - install
