#!/bin/bash

function usage() {
    echo "Usage:"
    echo "          init [options] [-p <section>]"
    echo
    echo "This little script runs any series of commands written"
    echo "in ./README.md."
    echo
    echo "  -d              Dry run"
    echo "  -h              Help!"
    echo "  -p <section>    Read commands from the <section>"
    echo "  -s              Show all sections"
}

function showSections() {
    if [[ $# -eq 0 ]] || [[ "$1" == "-p" ]]; then
        grep -o -e "^#.*" < README.md
        exit 1
    fi
}

function skipToSection() {
    local IFS="$(printf '\n')"
    while read line; do
        # This skips every line until $keyword
        [[ "$line" == "# $section" ]] && break
    done

    cat
}

function readSection() {
    local IFS="$(printf ' \n')"
    while read line; do
        [[ -z "$line" ]] && break
        echo "$line"
    done
}

function run() {
    [[ $dry == 'true' ]] && cat || sh
}

DOTFILES=(bash_aliases Xmodmap)
keyword="$1"
section=''
dry='false'

while getopts "dp:hs" opt; do
    case "$opt" in
        d)  dry='true'
            ;;
        p)  section=$OPTARG
            ;;
        s)  showSections
            exit 1
            ;;
        h)  usage 2>/dev/null
            exit 1
            ;;
        \?) echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        *)  usage 2>/dev/null
            exit 1
            ;;
    esac
done

skipToSection "$section" < README.md | readSection | run


# for i in "${DOTFILES[@] }"; do
#     echo  "$(pwd)/.$i <- $HOME/.$i"
#     [[ -L "$HOME/.$i" ]] && rm "$HOME/.$i"
#     ln -s "$(pwd)/.$i" "$HOME/.$i"
# done
