---
- name: Setup basic tools for fresh OS
  hosts: all
  vars:
    - user_name: "jasu"
    - password: "password"
    - guestaddition_version: "5.1.16"
    - vbox: true
    - vagrant: false
  roles:
    - users
    # - common
    # - vim
