# -*- mode: ruby -*-
# vi: set ft=ruby :

vbox_name = "hoptec"
user_name = "jasu"
user_password = "vagrant"
guestadditions_version="5.1.16"
# guestadditions_version=`vboxmanage --version | cut -d' ' -f 2`

Vagrant.configure("2") do |config|
  # NOTE: You must have vagrant-vbguest plugin installed for Debian
  # $ vagrant plugin install vagrant-vbguest
  config.vm.box = "debian/jessie64"
  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "C:/Users/jasu/Desktop/shared", "/shared"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = vbox_name
  
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update -y
  apt-get install -y git
  git -C /home/vagrant clone https://github.com/jasu0/reboot
  SHELL
end
