# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "master" do |node|
    node.vm.box = "debian/stretch64"
    node.vm.network "private_network", ip: "10.1.1.1"
    node.vm.network "public_network"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.gui = false
      vb.memory = "2048"
    end
  end

  # Generate SSH keys
  # $ ssh-keygen.exe -f keys/private_key -t rsa
  # $ ssh-keygen.exe -f keys/private_key -y > keys/public_key
  config.vm.provision "file", source: "keys/public_key", destination: "/home/vagrant/.ssh/authorized_keys"
  config.vm.provision "file", source: "keys/private_key", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "keys/private_key", destination: "/home/vagrant/.ssh/id_rsa.pub"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y vim curl wget tree screen console-data
  SHELL
end
