---

# TODO

- block:
  - name: "create backup directories"
    file:
      path: "{{ backup_target }}/{{ item }}"
      state: "directory"
    become: true
    with_items:
    - "snapshots"
    - "archives"
