---

- name: Install Vagrant specific packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - xfce4
  - xfce4-terminal
  - lightdm
  when: "{{ vagrant }}"

- name: "Check if Guest Additions exists"
  action: "shell lsmod | grep vboxsf"
  register: vboxsf_exists
  ignore_errors: true


- block:
  - name: m-a prepare
    shell: m-a prepare

  - stat:
      path: "/opt/VBoxGuestAdditions_{{ guestaddition_version }}.iso"
    register: imagefile

  - name: Download image
    uri:
      url: "http://download.virtualbox.org/virtualbox/{{ item }}/VBoxGuestAdditions_{{ item }}.iso"
      dest: "/opt/VBoxGuestAdditions_{{ item }}.iso"
    when: imagefile.stat.exists == false
    with_items:
      - "{{ guestaddition_version }}"

  - name: Mount image
    mount:
      fstype: "iso9660"
      opts: "loop"
      name: "/mnt"
      src: "/opt/VBoxGuestAdditions_{{ item }}.iso"
      state: "mounted"
    with_items:
      - "{{ guestaddition_version }}"

  - name: Install
    shell: "/mnt/VBoxLinuxAdditions.run --nox11"

  - name: Umount image
    mount:
      fstype: "none"
      name: "/mnt"
      src: "none"
      state: "unmounted"

  # - name: Remove image
  #   file:
  #     path: "/opt/VBoxGuestAdditions_{{ item }}.iso"
  #   with_items:
  #     - "{{ guestaddition_version }}"

  when:
  - vbox
  - vboxsf_exists.failed is defined
  tags:
  - install
  - test
