---

- block:
  - name: "create backup directories"
    file:
      path: "{{ backup_target }}/{{ item }}"
      state: "directory"
      owner: "root"
      group: "root"
      mode: 0700
    become: true
    with_items:
    - "snapshots"
    - "archives"

  - name: "create directory for executable"
    file:
      path: "{{ item }}"
      state: "directory"
    become: true
    with_items:
    - "{{ backup_script_path | dirname }}"

  - name: "copy backup.sh"
    template:
      src: "./{{ item }}.j2"
      dest: "{{ item }}"
      mode: 0544
    become: true
    with_items:
    - "{{ backup_script_path }}"

  - name: "timer backup"
    cron:
      name: "backup data directory"
      job: "{{ backup_script_path }} backup"
      minute: 30
      hour: 5
      weekday: 0
      user: "root"
    become: true
