
# ~/.bash_profile
#

if [[ $- != *i* ]] && [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi

bind '"": backward-word'
bind '"": forward-word'

export PATH=/opt/bin/:$HOME/bin/:$PATH
export LD_LIBRARY_PATH+=/usr/local/lib:/opt/lib
export C_INCLUDE_PATH+=/opt/include
export VISUAL=vim

# Lock computer if X is closed
if [[ $LOGNAME == "jasu" && -z "$SSH_TTY" && -z "$DISPLAY" ]]; then
    exec startx
    logout
fi
