---

- block:
  - name: "install base packages"
    apt:
      name: "{{ item }}"
      state: "present"
    become: true
    loop:
    - "{{ x11_packages }}"
    - "{{ window_manager_packages[window_manager] | default([]) }}"
    - "{{ window_manager_packages_additional[window_manager] | default([]) }}"

  when: window_manager is defined

# Configuration
- block:

  - file:
      path: "{{ item }}"
      state: "directory"
    with_items:
    - "/etc/lightdm/lightdm.conf.d"

  - template:
      src: "./{{ item }}.j2"
      dest: "{{ item }}"
    become: true
    with_items:
    - "/etc/lightdm/lightdm.conf.d/custom.conf"

  when: window_manager is defined

- block:

  - set_fact:
      config_dirs:
      - "/etc/X11/xorg.conf.d/10-keyboard-layout.conf"

  - name: "ensure that common config directories exists"
    file:
      path: "{{ item | dirname }}"
      state: "directory"
    become: true
    with_items:
    - "{{ config_dirs }}"

  - name: "copy common config files"
    template:
      src: "./{{ item }}.j2"
      dest: "{{ item }}"
    become: true
    with_items:
    - "{{ config_dirs }}"

  when: window_manager is defined and false
