---

- block:
  - name: "ensure that common config directories exists"
    file:
      path: "{{ item | dirname }}"
      state: "directory"
    become: true
    with_items:
    - "/etc/lightdm/lightdm.conf.d/10-autologin.conf"
    - "/etc/X11/xorg.conf.d/10-keyboard-layout.conf"

  - name: "copy common config files"
    template:
      src: "./{{ item }}.j2"
      dest: "{{ item }}"
    become: true
    with_items:
    - "/etc/lightdm/lightdm.conf.d/10-autologin.conf"
    - "/etc/X11/xorg.conf.d/10-keyboard-layout.conf"

  - name: "copy user specific XFCE4 config"
    copy:
      src: "home/user/config/xfce4"
      dest: "/home/{{ os_user_uname }}/.config"
    become: true
    become_user: "{{ os_user_uname }}"
