---

- block:
  - name: "install base packages"
    apt:
      name: "{{ item }}"
      state: "present"
    become: true
    with_items:
    - "{{ xfce4_packages }}"
    - "{{ xfce4_packages_additional }}"

  - name: "ensure that common config directories exists"
    file:
      path: "{{ item | dirname }}"
      state: "directory"
    become: true
    with_items:
    - "/etc/lightdm/lightdm.conf.d/10-autologin.conf"
    - "/etc/X11/xorg.conf.d/10-keyboard-layout.conf"

  - name: "copy common config files"
    template:
      src: "./{{ item }}.j2"
      dest: "{{ item }}"
    become: true
    with_items:
    - "/etc/lightdm/lightdm.conf.d/10-autologin.conf"
    - "/etc/X11/xorg.conf.d/10-keyboard-layout.conf"

  - name: "copy user specific XFCE4 config"
    copy:
      src: "home/user/config/xfce4"
      dest: "/home/{{ item.uname }}/.config"
    become: true
    become_user: "{{ item.uname }}"
    with_items:
    - "{{ os_users }}"
