---

- block:
  - name: "install basepackages"
    apt:
      name: "{{ item }}"
      state: "present"
    become: true
    with_items:
    - "{{ window_manager_packages[window_manager] | default([]) }}"
    - "{{ window_manager_packages_additional[window_manager] | default([]) }}"

  - name: "post-configure window manager"
    include_tasks: "deploy-{{ window_manager }}.yml"
