---
# This roles install Virtual Box's Guest Additions

- name: "check if Guest Additions exists"
  action: "shell lsmod | grep vboxsf"
  register: r_vboxsf_exists
  ignore_errors: true


- block:
  - name: "m-a prepare"
    shell: "m-a prepare"
    become: true

  - stat:
      path: "/tmp/VBoxGuestAdditions_{{ guestaddition_version }}.iso"
    register: r_imagefile

  - name: "download guestaddititions image"
    uri:
      url: "http://download.virtualbox.org/virtualbox/{{ item }}/VBoxGuestAdditions_{{ item }}.iso"
      dest: "/tmp/VBoxGuestAdditions_{{ item }}.iso"
    when: r_imagefile.stat.exists == false
    with_items:
    - "{{ guestaddition_version }}"

  - name: "mount image"
    mount:
      fstype: "iso9660"
      opts: "loop"
      name: "/mnt"
      src: "/tmp/VBoxGuestAdditions_{{ item }}.iso"
      state: "mounted"
    become: true
    with_items:
    - "{{ guestaddition_version }}"

  - name: "install guest additions"
    shell: "/mnt/VBoxLinuxAdditions.run --nox11"
    become: true
    when:
    - r_vboxsf_exists.failed is defined

  - name: "umount image"
    mount:
      fstype: "none"
      name: "/mnt"
      src: "none"
      state: "unmounted"
    become: true

  # - name: Remove image
  #   file:
  #     path: "/tmp/VBoxGuestAdditions_{{ item }}.iso"
  #   with_items:
  #     - "{{ guestaddition_version }}"

  when:
  - r_vboxsf_exists.failed is not defined
