---

- stat:
    path: "/usr/local/bin/vim"
  register: "r_vim"

- block:

  - name: "fetch vim"
    git:
      repo: "https://github.com/vim/vim"
      dest: "/tmp/vim"

# How to compile
# $ apt-get install python3-dev
# $ ./configure
# --prefix=/usr/local
# --enable-python3interp=yes
# --with-python3-config-dir=/usr/lib/python3.5/config

  - name: "configure"
    command: "./configure --prefix=/usr/local/"
    args:
      chdir: "/tmp/vim/"

  - name: "make"
    command: "/usr/bin/make"
    args:
      chdir: "/tmp/vim/"

  - name: "make install"
    command: "/usr/bin/make install"
    args:
      chdir: "/tmp/vim/"
    become: true

# Vim plugins

- block:

  - name: "ensure plugin directories exists"
    file:
      dest: "/home/{{ os_user_uname }}/{{ item }}"
      state: "directory"
      owner: "{{ os_user_uname }}"
      group: "{{ os_user_uname }}"
      recurse: true
    become: true
    become_user: "{{ os_user_uname }}"
    with_items:
    - ".vim"
    - ".vim/bundle"

  - name: "git clone plugins"
    git:
      repo: "https://github.com/{{ item }}"
      dest: "/home/{{ os_user_uname }}/.vim/bundle/{{ item | basename }}"
    become: true
    become_user: "{{ os_user_uname }}"
    with_items:
    - "{{ vim_plugins }}"
    - "{{ vim_plugins_additional }}"

  - name: "symlink .vimrc"
    file:
      dest: "/home/{{ os_user_uname }}/.vimrc"
      src: "/home/{{ os_user_uname }}/.vim/bundle/{{ vimrc_path }}"
      state: "link"
    become: true
    become_user: "{{ os_user_uname }}"

  - name: "install plugins"
    shell: "vim +PluginInstall +qa!"
    become: true
    become_user: "{{ os_user_uname }}"
