---

- stat:
    path: "/usr/local/bin/vim"
  register: "r_vim"

- block:

  - name: "fetch vim"
    git:
      repo: "https://github.com/vim/vim"
      dest: "/tmp/vim"
  
  - name: "configure"
    command: "./configure --prefix=/usr/local/"
    args:
      chdir: "/tmp/vim/"
  
  - name: "make"
    command: "/usr/bin/make"
    args:
      chdir: "/tmp/vim/"
  
  - name: "make install"
    command: "/usr/bin/make install"
    args:
      chdir: "/tmp/vim/"
    become: true

  when:
  - "r_vim.stat.exists == False"


# Vim plugins

- stat:
    path: "/home/{{ user_name }}/.vim/bundle/VimBox-rc"
  become: true
  become_user: "{{ user_name }}"
  register: "r_vimbox"

- block:

  - name: "create .vim folder"
    file:
      dest: "/home/{{ user_name }}/.vim/bundle"
      state: "directory"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      recurse: true
    become: true
    become_user: "{{ user_name }}"

  - name: "git clone plugins"
    git:
      repo: "https://github.com/{{ item.user }}/{{ item.repo }}"
      dest: "/home/{{ user_name }}/.vim/bundle/{{ item.repo }}"
    become: true
    become_user: "{{ user_name }}"
    with_items:
    - user: "VundleVim"
      repo: "Vundle.vim"
    - user: "jasu0"
      repo: "VimBox-rc"
  
  - name: "symlink .vimrc"
    file:
      dest: "/home/{{ user_name }}/.vimrc"
      src: "/home/{{ user_name }}/.vim/bundle/VimBox-rc/vimrc"
      state: "link"
    become: true
    become_user: "{{ user_name }}"

  - name: "install plugins"
    shell: "vim +PluginInstall"
    become: true
    become_user: "{{ user_name }}"

  when:
  - r_vim.stat.exists == True

