---

- stat:
    path: "/usr/local/bin/vim"
  register: "r_custom_vim_installation"

- block:

  - name: "fetch vim"
    git:
      repo: "https://github.com/vim/vim"
      dest: "/tmp/vim"

  - name: "configure"
    command: "./configure --prefix=/usr/local/"
    args:
      chdir: "/tmp/vim/"

  - name: "make"
    command: "/usr/bin/make"
    args:
      chdir: "/tmp/vim/"

  - name: "make install"
    command: "/usr/bin/make install"
    args:
      chdir: "/tmp/vim/"
    become: true

  when: (compile_vim == 'true')

- include_tasks: "plugins.yml"
  loop:
  - "{{ vim_users }}"
  loop_control:
    loop_var: vim_user
  when: vim_user | length > 0
