---

- stat:
    path: "/usr/local/bin/vim"
  register: "r_vim"

- block:

  - name: "fetch vim"
    git:
      repo: "https://github.com/vim/vim"
      dest: "/tmp/vim"
  
  - name: "configure"
    command: "./configure --prefix=/usr/local/"
    args:
      chdir: "/tmp/vim/"
  
  - name: "make"
    command: "/usr/bin/make"
    args:
      chdir: "/tmp/vim/"
  
  - name: "make install"
    command: "/usr/bin/make install"
    args:
      chdir: "/tmp/vim/"
    become: true

# Vim plugins

- block:

  - name: "ensure plugin directories exists"
    file:
      dest: "/home/{{ item.0 }}/{{ item.1 }}"
      state: "directory"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      recurse: true
    become: true
    become_user: "{{ user_name }}"
    with_nested:
    - "{{ user_name }}"
    - [".vim", ".vim/bundle"]

  - name: "git clone plugins"
    git:
      repo: "https://github.com/{{ item }}"
      dest: "/home/{{ user_name }}/.vim/bundle/{{ item | basename }}"
    become: true
    become_user: "{{ user_name }}"
    with_items:
    - "{{ vim_plugins }}"
  
  - name: "symlink .vimrc"
    file:
      dest: "/home/{{ user_name }}/.vimrc"
      src: "/home/{{ user_name }}/.vim/bundle/{{ vimrc_path }}"
      state: "link"
    become: true
    become_user: "{{ user_name }}"

  - name: "install plugins"
    shell: "vim +PluginInstall +qa!"
    become: true
    become_user: "{{ user_name }}"
