---

- stat:
    path: "/usr/local/bin/vim"
  register: "r_vim"

- block:

  - name: "fetch vim"
    git:
      repo: "https://github.com/vim/vim"
      dest: "/tmp/vim"

  - name: "configure"
    command: "./configure --prefix=/usr/local/"
    args:
      chdir: "/tmp/vim/"

  - name: "make"
    command: "/usr/bin/make"
    args:
      chdir: "/tmp/vim/"

  - name: "make install"
    command: "/usr/bin/make install"
    args:
      chdir: "/tmp/vim/"
    become: true

# Vim plugins

- block:

  - name: "ensure plugin directories exists"
    file:
      dest: "/home/{{ item.0 }}/{{ item.1 }}"
      state: "directory"
      owner: "{{ os_users[0].uname }}"
      group: "{{ os_users[0].uname }}"
      recurse: true
    become: true
    become_user: "{{ os_users[0].uname }}"
    with_nested:
    - "{{ os_users[0].uname }}"
    - [".vim", ".vim/bundle"]

  - name: "git clone plugins"
    git:
      repo: "https://github.com/{{ item }}"
      dest: "/home/{{ os_users[0].uname }}/.vim/bundle/{{ item | basename }}"
    become: true
    become_user: "{{ os_users[0].uname }}"
    with_items:
    - "{{ vim_plugins }}"

  - name: "symlink .vimrc"
    file:
      dest: "/home/{{ os_users[0].uname }}/.vimrc"
      src: "/home/{{ os_users[0].uname }}/.vim/bundle/{{ vimrc_path }}"
      state: "link"
    become: true
    become_user: "{{ os_users[0].uname }}"

  - name: "install plugins"
    shell: "vim +PluginInstall +qa!"
    become: true
    become_user: "{{ os_users[0].uname }}"
