---

- stat:
    path: "/usr/local/bin/vim"
  register: "r_vim"

- block:

  - name: "fetch vim"
    git:
      repo: "https://github.com/vim/vim"
      dest: "/tmp/vim"

  - name: "configure"
    command: "./configure --prefix=/usr/local/"
    args:
      chdir: "/tmp/vim/"

  - name: "make"
    command: "/usr/bin/make"
    args:
      chdir: "/tmp/vim/"

  - name: "make install"
    command: "/usr/bin/make install"
    args:
      chdir: "/tmp/vim/"
    become: true

- include: "plugins.yml"
  vars:
    vim_user: "{{ item }}"
  with_items:
  - "{{ vim_users }}"
