---

- name: "ensure plugin directories exists"
  file:
    dest: "/home/{{ vim_user }}/{{ item }}"
    state: "directory"
    owner: "{{ vim_user }}"
    group: "{{ vim_user }}"
    recurse: true
  become: true
  with_items:
  - ".vim"
  - ".vim/bundle"

- name: "git clone plugins"
  git:
    repo: "https://github.com/{{ item }}"
    dest: "/home/{{ vim_user }}/.vim/bundle/{{ item | basename }}"
  become: true
  become_user: "{{ vim_user }}"
  with_items:
  - "{{ vim_plugins }}"
  - "{{ vim_plugins_additional }}"

- name: "symlink .vimrc"
  file:
    dest: "/home/{{ vim_user }}/.vimrc"
    src: "/home/{{ vim_user }}/.vim/bundle/{{ vimrc_path }}"
    state: "link"
  become: true
  become_user: "{{ vim_user }}"

- name: "install plugins"
  shell: "vim +PluginInstall +qa!"
  become: true
  become_user: "{{ vim_user }}"
