---
- name: Install basic tools
  apt: name={{item}} state=present
  with_items:
       - dbus-x11
       - git
       - gitk
       - libgtk2.0-dev
       - libx11-dev
       - libxt-dev
       - ncurses-dev
       - python-dev
       - xsel
