---
- name: Setup basic tools for fresh OS
  hosts: localhost
  vars:
  - os_users:
    - uname: "jasu"
      pword: "password"
  - user_name: "jasu"
  - password: "password"
  - guestaddition_version: "5.1.22"
  - vagrant: true
  roles:
  - base
  # - java8
  - users
  - vbox
  - vim
